FROM openshift/redhat-openjdk18-openshift:1.8
COPY . /src
WORKDIR /src
RUN mvn build

FROM tomcat:8-jre8
RUN rm -rf /usr/local/tomcat/webapps/*
COPY target/gameoflife.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
